### ISSUE TITLE
Improve links metadata

### ISSUE THREAD

**Issue by silvester-pari** [EOEPCA/open-science-catalog-metadata#8]
In the products CSV, there are `Website`, `Access`, `Documentation`, and `DOI` fields with URLs, but in the product JSONs most of these links are "rel" "via" and there is no way for the frontend to properly display this as requested.

Example: https://github.com/EOEPCA/open-science-catalog-metadata/blob/e924e19e29db000f74dc55dca2f25559c625358a/data/products/product-1.json#L58-L71

**Comment by constantinius** [comment]
Done with https://github.com/EOEPCA/open-science-catalog-builder/commit/43767fa2044cf46079a994b5740f3029ae1415d7, https://github.com/EOEPCA/open-science-catalog-metadata/commit/fff1202b3a9c5d083c849a468f8138e0f7281bc7 and https://github.com/EOEPCA/open-science-catalog-metadata/commit/8060d0ec95eb3a140413154f678d624a7ce78f3f
